// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIZ03sebmQcO_AYPQ1c-0gLmcu_wpqOiw',
    appId: '1:573158375117:web:be02b5c64b88f49f9d3384',
    messagingSenderId: '573158375117',
    projectId: 'patternpulse-342b2',
    authDomain: 'patternpulse-342b2.firebaseapp.com',
    storageBucket: 'patternpulse-342b2.appspot.com',
    measurementId: 'G-70NJKHN353',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyMeIKRaJLK3EIt-ZCHI3kQSr3Hg2IWXg',
    appId: '1:573158375117:android:5f645890a0ae56f09d3384',
    messagingSenderId: '573158375117',
    projectId: 'patternpulse-342b2',
    storageBucket: 'patternpulse-342b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHdWBGVJJ04hDtU-IBQBie5Q5hnA42iYk',
    appId: '1:573158375117:ios:ea91077222b2e5549d3384',
    messagingSenderId: '573158375117',
    projectId: 'patternpulse-342b2',
    storageBucket: 'patternpulse-342b2.appspot.com',
    iosBundleId: 'com.example.patternpulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHdWBGVJJ04hDtU-IBQBie5Q5hnA42iYk',
    appId: '1:573158375117:ios:ea91077222b2e5549d3384',
    messagingSenderId: '573158375117',
    projectId: 'patternpulse-342b2',
    storageBucket: 'patternpulse-342b2.appspot.com',
    iosBundleId: 'com.example.patternpulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIZ03sebmQcO_AYPQ1c-0gLmcu_wpqOiw',
    appId: '1:573158375117:web:8fb7c6045c65c87a9d3384',
    messagingSenderId: '573158375117',
    projectId: 'patternpulse-342b2',
    authDomain: 'patternpulse-342b2.firebaseapp.com',
    storageBucket: 'patternpulse-342b2.appspot.com',
    measurementId: 'G-35MDRRQLKN',
  );
}
